name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Build binaries
      run: |
        mkdir -p build
        
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o build/har-tui-linux-amd64 cmd/har-tui/main.go
        GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o build/har-tui-linux-arm64 cmd/har-tui/main.go
        GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o build/har-tui-darwin-amd64 cmd/har-tui/main.go
        GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o build/har-tui-darwin-arm64 cmd/har-tui/main.go
        GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o build/har-tui-windows-amd64.exe cmd/har-tui/main.go
        
        # Generate checksums
        cd build
        sha256sum * > checksums.sha256
        cd ..
        
        # Make binaries executable
        chmod +x build/har-tui-*
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/*
        body: |
          ## 🐱 HAR TUI DELUXE ${{ github.ref_name }}
          
          ### Downloads
          - **Linux (AMD64)**: `har-tui-linux-amd64`
          - **Linux (ARM64)**: `har-tui-linux-arm64` 
          - **macOS (Intel)**: `har-tui-darwin-amd64`
          - **macOS (Apple Silicon)**: `har-tui-darwin-arm64`
          - **Windows (AMD64)**: `har-tui-windows-amd64.exe`
          
          ### Installation
          1. Download the appropriate binary for your platform
          2. Make it executable: `chmod +x har-tui-*`
          3. Move to PATH: `sudo mv har-tui-* /usr/local/bin/har-tui`
          4. Run: `har-tui your-file.har`
          
          ### Checksums
          Verify your download with `checksums.sha256`
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}